### ISSUE TITLE
'No such file or directory' error

### ISSUE THREAD

**Issue by nishchalk** [surya945/RTSP_Android#1]
Unable to save csv file or any other file format using this app.
Following is the output of logcat.

......
V/Accelerometer: t=1551691806530 x=0.643829 y=0.189896 z=9.903168
I/zygote64: Do partial code cache collection, code=501KB, data=312KB
I/zygote64: After code cache collection, code=501KB, data=312KB
    Increasing code cache capacity to 2MB
W/System.err: java.io.FileNotFoundException: /storage/emulated/0/AccelerometerData/trial.csv (No such file or directory)
W/System.err:     at java.io.FileOutputStream.open0(Native Method)
        at java.io.FileOutputStream.open(FileOutputStream.java:287)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:223)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:171)
W/System.err:     at java.io.FileWriter.<init>(FileWriter.java:90)
        at mbreath.com.rtsp_android.MainActivity.generateNoteOnSD(MainActivity.java:108)
        at mbreath.com.rtsp_android.MainActivity.onSaveClick(MainActivity.java:95)
        at java.lang.reflect.Method.invoke(Native Method)
        at android.support.v7.app.AppCompatViewInflater$DeclaredOnClickListener.onClick(AppCompatViewInflater.java:385)
        at android.view.View.performClick(View.java:6304)
        at android.view.View$PerformClick.run(View.java:24803)
        at android.os.Handler.handleCallback(Handler.java:794)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:176)
        at android.app.ActivityThread.main(ActivityThread.java:6635)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:823)

**Comment by nishchalk** [comment]
The toast saying "Please enter the file name" is not triggered when fileName = null
